name: chicago_311
channels:
  - DAP python
  - conda
dependencies:
  - python=3.11
  - pandas
  - numpy
  - geopandas
  - altair
  - vl-convert-python
  - matplotlib
  - shapely
  - requests
  - pyarrow
  - streamlit
  - plotly
  - jupyter
